#!/usr/bin/env perl
use Mojolicious::Lite;

get '/' => sub {
  my $self = shift;
  my $entry = $self->param('body') || '';
  $self->stash(entry => $entry);
  $self->render('index');
};

post '/post' => sub {
  my $self = shift;
  my $entry = $self->param('body') || '';
  $self->stash(entry => $entry);
  $self->render('post');
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'BBS';

%= form_for '/post' => method => 'POST' => begin
  %= text_field 'body'
  %= submit_button '投稿する'
% end

@@ post.html.ep
% layout 'default';
% title 'BBS';

%= form_for '/post' => method => 'POST' => begin
  %= text_field 'body'
  %= submit_button '投稿する'
% end
<p><%= $entry %></p>

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>
