#!/usr/bin/env perl
use Mojolicious::Lite;

# Documentation browser under "/perldoc"
plugin 'PODRenderer';

get '/' => sub {
    my $self = shift;
    $self->stash( title => 'Hello' );
    $self->render('index');
};

get '/profile' => sub {
    my $self = shift;

    $self->stash(
        name     => 'maezawa',
        hobby    => '登山',
        language => 'Perl',

    );

    $self->render('profile');
};

get '/profile/:name' => sub {
    my $self = shift;

    my %profile_tbl = (
        'maezawa1' => { hobby => '登山1', language => 'perl1' },
        'maezawa2' => { hobby => '登山2', language => 'perl2' },
        'maezawa3' => { hobby => '登山3', language => 'perl3' },
    );

    $self->stash( $profile_tbl{ $self->stash('name') } );
    $self->render('profile');
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'Welcome';
Welcome to the Mojolicious real-time web framework!

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>

@@ profile.html.ep
<html>
<head><title><%= $name %>のプロフィール</title></head>
<body style='padding: 30px;'>
  私の名前は<%= $name %>です.<br>
  趣味は<%= $hobby %>で, 好きなプログラミング言語は<%= $language %>です.
</body>
</html>
